languageCode = 'en-us'
title = 'The Wonderful World of Organic Geometry'
theme = 'hugo-book'
[markup]
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe=true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['$', '$']]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true
[params]
  math = true
  BookSection = '*'
  BookLogo = 'projgeom.png'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'